# Generated by Django 5.2.3 on 2025-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('guest', 'Гость'), ('standard', 'Пользователь')], default='guest', max_length=20),
        ),
    ]
